enum FlagEnum {
  afghanistan(["afghanistan"], "af"),
  albania(["albania"], "al"),
  algeria(["algeria"], "dz"),
  american(["american samoa"], "as"),
  andorra(["andorra"], "ad"),
  angola(["angola"], "ao"),
  anguilla(["anguilla"], "ai"),
  antarctica(["antarctica"], "aq"),
  antigua(["antigua and barbuda"], "ag"),
  argentina(["argentina"], "ar"),
  aruba(["aruba"], "aw"),
  armenia(["armenia"], "am"),
  australia(["australia"], "au"),
  austria(["austria"], "at"),
  azerbaijan(["azerbaijan"], "az"),
  bahamas(["bahamas (the)"], "bs"),
  bahrain(["bahrain"], "bh"),
  bangladesh(["bangladesh"], "bd"),
  barbados(["barbados"], "bb"),
  belarus(["belarus"], "by"),
  belgium(["belgium"], "be"),
  belize(["belize"], "bz"),
  benin(["benin"], "bj"),
  bermuda(["bermuda"], "bm"),
  bhutan(["bhutan"], "bt"),
  bolivia(["bolivia (plurinational state of)"], "bo"),
  bonaire(["bonaire, sint eustatius and saba"], "bq"),
  bosnia(["bosnia and herzegovina"], "ba"),
  botswana(["botswana"], "bw"),
  bouvet(["bouvet island"], "bv"),
  brazil(["brazil"], "br"),
  british(["british indian ocean territory (the)"], "io"),
  brunei(["brunei darussalam"], "bn"),
  bulgaria(["bulgaria"], "bg"),
  burkina(["burkina faso"], "bf"),
  burundi(["burundi"], "bi"),
  cabo(["cabo verde"], "cv"),
  cambodia(["cambodia"], "kh"),
  cameroon(["cameroon"], "cm"),
  canada(["canada"], "ca"),
  cayman(["cayman islands (the)"], "ky"),
  central(["central african republic (the)"], "cf"),
  chad(["chad"], "td"),
  chile(["chile"], "cl"),
  china(["china"], "cn"),
  christmas(["christmas island"], "cx"),
  cocos(["cocos (keeling) islands (the)"], "cc"),
  colombia(["colombia"], "co"),
  comoros(["comoros (the)"], "km"),
  congodemocratic(["congo (the democratic republic of the)"], "cd"),
  congo(["congo (the)"], "cg"),
  cook(["cook islands (the)"], "ck"),
  costa(["costa rica"], "cr"),
  croatia(["croatia"], "hr"),
  cuba(["cuba"], "cu"),
  curacao(["curaçao"], "cw"),
  cyprus(["cyprus"], "cy"),
  czechia(["czechia"], "cz"),
  cote(["côte d'ivoire"], "ci"),
  denmark(["denmark"], "dk"),
  djibouti(["djibouti"], "dj"),
  dominica(["dominica"], "dm"),
  dominican(["dominican republic (the)"], "do"),
  ecuador(["ecuador"], "ec"),
  egypt(["egypt"], "eg"),
  el(["el salvador"], "sv"),
  equatorial(["equatorial guinea"], "gq"),
  eritrea(["eritrea"], "er"),
  estonia(["estonia"], "ee"),
  eswatini(["eswatini"], "sz"),
  ethiopia(["ethiopia"], "et"),
  falkland(["falkland islands (the) [malvinas]"], "fk"),
  faroe(["faroe islands (the)"], "fo"),
  fiji(["fiji"], "fj"),
  finland(["finland"], "fi"),
  france(["france"], "fr"),
  frenchguiana(["french guiana"], "gf"),
  frenchpolynesia(["french polynesia"], "pf"),
  frenchsouthernterritories(["french southern territories (the)"], "tf"),
  gabon(["gabon"], "ga"),
  gambia(["gambia (the)"], "gm"),
  georgia(["georgia"], "ge"),
  germany(["germany"], "de"),
  ghana(["ghana"], "gh"),
  gibraltar(["gibraltar"], "gi"),
  greece(["greece"], "gr"),
  greenland(["greenland"], "gl"),
  grenada(["grenada"], "gd"),
  guadeloupe(["guadeloupe"], "gp"),
  guam(["guam"], "gu"),
  guatemala(["guatemala"], "gt"),
  guernsey(["guernsey"], "gg"),
  guinea(["guinea"], "gn"),
  guineaBissau(["guinea-bissau"], "gw"),
  guyana(["guyana"], "gy"),
  haiti(["haiti"], "ht"),
  heard(["heard island and mcdonald islands"], "hm"),
  holy(["holy see (the)"], "va"),
  honduras(["honduras"], "hn"),
  hong(["hong kong"], "hk"),
  hungary(["hungary"], "hu"),
  iceland(["iceland"], "is"),
  india(["india"], "in"),
  indonesia(["indonesia"], "id"),
  iran(["iran (islamic republic of)"], "ir"),
  iraq(["iraq"], "iq"),
  ireland(["ireland"], "ie"),
  isle(["isle of man"], "im"),
  israel(["israel"], "il"),
  italy(["italy"], "it"),
  jamaica(["jamaica"], "jm"),
  japan(["japan"], "jp"),
  jersey(["jersey"], "je"),
  jordan(["jordan"], "jo"),
  kazakhstan(["kazakhstan"], "kz"),
  kenya(["kenya"], "ke"),
  kiribati(["kiribati"], "ki"),
  koreaDemocratic(["korea (the democratic people's republic of)"], "kp"),
  korearepublic(["korea (the republic of)"], "kr"),
  kuwait(["kuwait"], "kw"),
  kyrgyzstan(["kyrgyzstan"], "kg"),
  lao(["lao people's democratic republic (the)"], "la"),
  latvia(["latvia"], "lv"),
  lebanon(["lebanon"], "lb"),
  lesotho(["lesotho"], "ls"),
  liberia(["liberia"], "lr"),
  libya(["libya"], "ly"),
  liechtenstein(["liechtenstein"], "li"),
  lithuania(["lithuania"], "lt"),
  luxembourg(["luxembourg"], "lu"),
  macao(["macao"], "mo"),
  madagascar(["madagascar"], "mg"),
  malawi(["malawi"], "mw"),
  malaysia(["malaysia"], "my"),
  maldives(["maldives"], "mv"),
  mali(["mali"], "ml"),
  malta(["malta"], "mt"),
  marshall(["marshall islands (the)"], "mh"),
  martinique(["martinique"], "mq"),
  mauritania(["mauritania"], "mr"),
  mauritius(["mauritius"], "mu"),
  mayotte(["mayotte"], "yt"),
  mexico(["mexico"], "mx"),
  micronesia(["micronesia (federated states of)"], "fm"),
  moldova(["moldova (the republic of)"], "md"),
  monaco(["monaco"], "mc"),
  mongolia(["mongolia"], "mn"),
  montenegro(["montenegro"], "me"),
  montserrat(["montserrat"], "ms"),
  morocco(["morocco"], "ma"),
  mozambique(["mozambique"], "mz"),
  myanmar(["myanmar"], "mm"),
  namibia(["namibia"], "na"),
  nauru(["nauru"], "nr"),
  nepal(["nepal"], "np"),
  netherlands(["netherlands (the)"], "nl"),
  newCalendonia(["new caledonia"], "nc"),
  newzealand(["new zealand"], "nz"),
  nicaragua(["nicaragua"], "ni"),
  niger(["niger (the)"], "ne"),
  nigeria(["nigeria"], "ng"),
  niue(["niue"], "nu"),
  norfolk(["norfolk island"], "nf"),
  northern(["northern mariana islands (the)"], "mp"),
  norway(["norway"], "no"),
  oman(["oman"], "om"),
  pakistan(["pakistan"], "pk"),
  palau(["palau"], "pw"),
  palestine(["palestine, state of"], "ps"),
  panama(["panama"], "pa"),
  papua(["papua new guinea"], "pg"),
  paraguay(["paraguay"], "py"),
  peru(["peru"], "pe"),
  philippines(["philippines (the)"], "ph"),
  pitcairn(["pitcairn"], "pn"),
  poland(["poland"], "pl"),
  portugal(["portugal"], "pt"),
  puerto(["puerto rico"], "pr"),
  qatar(["qatar"], "qa"),
  republic(["republic of north macedonia"], "mk"),
  romania(["romania"], "ro"),
  russian(["russian federation", "russia"], "ru"),
  rwanda(["rwanda"], "rw"),
  reunion(["réunion"], "re"),
  saintBarthelemy(["saint barthélemy"], "bl"),
  saintHelena(["saint helena, ascension and tristan da cunha"], "sh"),
  saintKitts(["saint kitts and nevis"], "kn"),
  saintLucia(["saint lucia"], "lc"),
  saintMartin(["saint martin (french part)"], "mf"),
  saintPierre(["saint pierre and miquelon"], "pm"),
  saintvincent(["saint vincent and the grenadines"], "vc"),
  samoa(["samoa"], "ws"),
  san(["san marino"], "sm"),
  sao(["sao tome and principe"], "st"),
  saudi(["saudi arabia"], "sa"),
  senegal(["senegal"], "sn"),
  serbia(["serbia"], "rs"),
  seychelles(["seychelles"], "sc"),
  sierra(["sierra leone"], "sl"),
  singapore(["singapore"], "sg"),
  sint(["sint maarten (dutch part)"], "sx"),
  slovakia(["slovakia"], "sk"),
  slovenia(["slovenia"], "si"),
  solomon(["solomon islands"], "sb"),
  somalia(["somalia"], "so"),
  southafrica(["south africa"], "za"),
  southGeorgia(["south georgia and the south sandwich islands"], "gs"),
  southSudan(["south sudan"], "ss"),
  spain(["spain", "spanish"], "es"),
  sri(["sri lanka"], "lk"),
  sudan(["sudan (the)"], "sd"),
  suriname(["suriname"], "sr"),
  svalbard(["svalbard and jan mayen"], "sj"),
  sweden(["sweden"], "se"),
  switzerland(["switzerland"], "ch"),
  syrian(["syrian arab republic"], "sy"),
  taiwan(["taiwan (province of china)"], "tw"),
  tajikistan(["tajikistan"], "tj"),
  tanzania(["tanzania, united republic of"], "tz"),
  thailand(["thailand"], "th"),
  timor(["timor-leste"], "tl"),
  togo(["togo"], "tg"),
  tokelau(["tokelau"], "tk"),
  tonga(["tonga"], "to"),
  trinidad(["trinidad and tobago"], "tt"),
  tunisia(["tunisia"], "tn"),
  turkey(["turkey"], "tr"),
  turkmenistan(["turkmenistan"], "tm"),
  turks(["turks and caicos islands (the)"], "tc"),
  tuvalu(["tuvalu"], "tv"),
  uganda(["uganda"], "ug"),
  ukraine(["ukraine"], "ua"),
  unitedarabEmirates(["united arab emirates (the)"], "ae"),
  unitedKingdom(
      ["united kingdom of great britain and northern ireland", "uk", "england"],
      "gb"),
  unitedStatesMinor(["united states minor outlying islands (the)"], "um"),
  unitedStatesamerica(["united states of america", "usa"], "us"),
  uruguay(["uruguay"], "uy"),
  uzbekistan(["uzbekistan"], "uz"),
  vanuatu(["vanuatu"], "vu"),
  venezuela(["venezuela (bolivarian republic of)"], "ve"),
  viet(["viet nam"], "vn"),
  virginIslandsBritish(["virgin islands (british)"], "vg"),
  virginIslandsUs(["virgin islands (u.s.)"], "vi"),
  wallis(["wallis and futuna"], "wf"),
  western(["western sahara"], "eh"),
  yemen(["yemen"], "ye"),
  zambia(["zambia"], "zm"),
  zimbabwe(["zimbabwe"], "zw"),
  aland(["Åland islands"], "ax");

  final List<String> alias;
  final String code;
  const FlagEnum(this.alias, this.code);

  static FlagEnum? getByAlias(String originalAlias) {
    final alias = originalAlias.length > 4
        ? originalAlias.substring(0, 4)
        : originalAlias;

    for (final item in FlagEnum.values) {
      final aliases = item.alias.toSet().join(",").toLowerCase();

      if (aliases.contains(alias.toLowerCase())) {
        return item;
      }
    }

    return null;
  }
}
